### ISSUE TITLE
Bad arg length for Socket::inet_ntoa

### ISSUE THREAD

**Issue by ghost** [eldy/AWStats#120]
Hmmm....was using @neilgierman 's fork before, but just updated to current eldy commit 0dd9142 and now getting:

`AH01215: Bad arg length for Socket::inet_ntoa, length is 0, should be 4 at /usr/local/awstats/wwwroot/cgi-bin/plugins/geoip2.pm line 200.`

**Comment by ghost** [comment]
Fixed by #115

**Comment by ghost** [comment]
@neilgierman - am getting "Undefined subroutine &main::TmpLookup_geoip called at /usr/local/awstats/wwwroot/cgi-bin/plugins/geoip2.pm line 121, <LOG> line 13483"

That position in the log was when I'd buggered up logging and the IP was coming back as "-"...so not sure why that should cause problems

`site.name - - - [18/Jan/2019:11:28:56 +1100] "GET /css/ HTTP/1.1" 200 6209 "https://site.name/" "Mozilla/5.0 (Android 8.0.0; Mobile; rev:65.0) Gecko/65.0 Firefox/65.0"`

**Comment by neilgierman** [comment]
That was a find and replace error. That should be TmpLookup_geoip2. I didn't see it because I still had the original GeoIP plugin enabled which defines that function. I assume you have the original GeoIP disabled so you don't have that function. I'll update my branch and make sure it is still good.

**Comment by ghost** [comment]
Thanks :)

Manual edit, now back to Socket problem (line 124 in this case now)

**Comment by ghost** [comment]
@neilgierman Line 120:
`if ((! $param)||($param eq "-")) { return ''; }`

**Comment by ghost** [comment]
Actually, I think this is better:

`if ($param !~ m/[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/) { return ''; }`
