### ISSUE TITLE
Feature Request: Exclude an IP from stats

### ISSUE THREAD

**Issue by dolibarr95** [eldy/AWStats#146]
Hi @eldy !

Is is possible to add the possibility to exclude an IP from the stats ?

Tks for reading

**Comment by dariodsa** [comment]
This is already possible. Check [this](https://github.com/eldy/awstats/blob/develop/wwwroot/cgi-bin/awstats.model.conf#L485) out.

**Comment by dolibarr95** [comment]
PERFECT tks a lot !!!!!

**Comment by dolibarr95** [comment]
Hi!
On my server I only find the conf file in tmp/ folder

```
/tmp/awstats
/tmp/awstats/awstats032017.domain2.domain.com.txt
/tmp/awstats/awstats.domain2.domain.com.conf
/tmp/awstats/awstats032017.domain.com.txt
/tmp/awstats/awstats.domain.com.conf
/tmp/awstats/awstats022016.domain.com.txt
/tmp/awstats/awstats012010.domain2.domain.com.txt
/tmp/awstats/awstats032018.domain.com.txt
/tmp/awstats/awstats012010.domain.com.txt
```
Editing (and restart server) this files change nothing.
Should I create this file somewhere else?

Tks

**Comment by dolibarr95** [comment]
Edited on my server : 
/usr/local/cpanel/etc/awstats.conf
