### ISSUE TITLE
GeoIP2 problems running on windows

### ISSUE THREAD

**Issue by visualperception** [eldy/AWStats#151]
Having installed GeoIP2 I am getting the following error when I run Awstats:

_Error: Plugin init for plugin 'geoip2' failed with return code: Undefined subroutine &main::Init_geoip2 called at (eval 2) line 1. (A module required by plugin might be missing)._

I have tried uninstall and reinstalling and I still get the error. I can't find any reference to Init_geoip2 in any of the GeoIP2 pm files.
I have also tried both PPM which seems to use an earlier version and cpan installs and both give the same error. The GeoIP2 install works without any errors.
I have reinstalled Awstats to make sure I have latest develop version files.

I have MaxMind-DB-Reader and MaxMind-DB-Common installed as well as GeoIP2
using Activestate Perl 64 bit. 

Can anyone shed any light on this or suggest what might be missing?

Thanks

**Comment by visualperception** [comment]
Does anyone have any suggestions?

**Comment by lambacck** [comment]
@visualperception I have a branch where I have it working. See the PR above. It seems like there's a case insensitive file issue somewhere that's causing the GeoIP2.pm module to conflict with the geoip2.pm plugin.

**Comment by visualperception** [comment]
Thanks, I will try your changes and let you know the result.

**Comment by visualperception** [comment]
I have applied this and all seems to be working OK now. Many thanks.

Also change your conf file to specify geoip_country
I guess awstats.model.conf and any other conf files in the distribution should be changed
