### ISSUE TITLE
7.8 - mime.pm - comma missing

### ISSUE THREAD

**Issue by wrvirtue** [eldy/AWStats#158]
Missing comma in mime.pm at end of line 79 
'gis',       'GIS File'

Causes server error.

**Comment by wrvirtue** [comment]
Oops, sorry. That should have been line 59, but you got it.

**Comment by wrvirtue** [comment]
Still not fixed in 7.8 zip download.  Can we expect that it will be any time soon?

**Comment by Bllacky** [comment]
send @eldy  an email and he will fix it: https://www.destailleur.fr/

**Comment by wrvirtue** [comment]
> send @eldy  an email and he will fix it: https://www.destailleur.fr/

Not really sure that I should do that.  In any case, it was easy for me to fix for myself and so not a problem for me personally.  Unfixed, however, it is a fatal error and so I'm rather surprised that correction in the 7.8 download package doesn't seem to be a top priority.

**Comment by Bllacky** [comment]
> 
> 
> > send @eldy  an email and he will fix it: https://www.destailleur.fr/
> 
> Not really sure that I should do that. In any case, it was easy for me to fix for myself and so not a problem for me personally. Unfixed, however, it is a fatal error and so I'm rather surprised that correction in the 7.8 download package doesn't seem to be a top priority.

It's about the community and helping everyone else. But ok.

**Comment by wrvirtue** [comment]
Well, you'll have to excuse my ignorance, but I was under the impression that this was the designated "community" forum for reporting bugs.  In fact, my report here has been acknowledged by a member of the development team and the required correction has actually been committed into the github project.

My assumption, therefore, was and is that I have thus done my appropriate part in whatever notification process is needed regarding that bug.  Unfortunately, for reasons that are completely unknown to me, the committed (and quite critical) correction has not yet found its way into the product download as I've also noted here.  Are you suggesting that I am somehow responsible to the community for dealing with that internal communication and production issue as well?  Sorry, but I must decline that role.

**Comment by Bllacky** [comment]
> 
> 
> Well, you'll have to excuse my ignorance, but I was under the impression that this was the designated "community" forum for reporting bugs. In fact, my report here has been acknowledged by a member of the development team and the required correction has actually been committed into the github project.
> 
> My assumption, therefore, was and is that I have thus done my appropriate part in whatever notification process is needed regarding that bug. Unfortunately, for reasons that are completely unknown to me, the committed (and quite critical) correction has not yet found its way into the product download as I've also noted here. Are you suggesting that I am somehow responsible to the community for dealing with that internal communication and production issue as well? Sorry, but I must decline that role.

I have no idea what you are talking about. All I can tell is that you are talking this very personal. I am sorry if I made any misunderstanding. I will contact eldy then, no problem.

**Comment by wrvirtue** [comment]
You're the one who seems to be making it personal.  I just reported a technical issue in the forum designated by the product author for doing so.  You seem to think I have some community obligation to do more.  In any case, I'm finished with it.  You do whatever you consider appropriate.
