### ISSUE TITLE
syntax error at lib/mime.pm

### ISSUE THREAD

**Issue by isigitas** [eldy/AWStats#160]
Awstats v7.8
My web server returns 500 error. Just checked log for cgi errors and found:

String found where operator expected at lib/mime.pm line 60, near "'ebook'"
	(Missing semicolon on previous line?)
syntax error at lib/mime.pm line 60, near "'ebook'"
Compilation failed in require at index.pl line 2239.
[27/Apr/2020:11:34:46 +0300]	CGI: [/usr/bin/perl index.pl ]	URI: /statai/index.pl?framename=mainright	Broken pipe

**Comment by isigitas** [comment]
Problem is solved, when i added comma after gis line at the end.

**Comment by Bllacky** [comment]
> 
> 
> Problem is solved, when i added comma after gis line at the end.

I might be wrong, but I think this was fixed in the last pull:
https://github.com/eldy/awstats/blob/develop/wwwroot/cgi-bin/lib/mime.pm

Though eldy said it will include this fix only in awstats 7.9 :-(

https://github.com/eldy/awstats/pull/159/commits/e5c32dd55ff7995933d84bd45076b09bba400986
