### ISSUE TITLE
Column mismatch with GeoIP2

### ISSUE THREAD

**Issue by Bllacky** [eldy/AWStats#162]
After struggling a bit I've managed to get AWStats to work with GeoIP2.
However, it seems in the new version I have there is a mismatch between columns.
Has anyone experienced this?

Here is a printscreen:
https://iapk2g.db.files.1drv.com/y4pAiNNCJQIFRp6m_jUqrpf9CABBpVLp_9qqhGYOlARId8zXkT48ccDVmNTbq15cCWgAVADXmAlDDdRNZ_v1wT2vI4i7San9Sh-aI_4kIIYMBbP6qJ30xQ_lZeSJVEGYSFA09UwgbCq8yaRf2mSafvISi4gQbgP1tPsTi9e46K-93zcGy3WhHsmjJ6N7n5tvzxG7p22Y518Sn4MbOuCS39JTxZqpBhuk6oWXfDKmMCrAhA/wrong%20columns.png?psid=1

**Comment by damien-giry** [comment]
Hi,

I think that I have the same problem (the link to your print screen is not working for me).

![Snap1](https://user-images.githubusercontent.com/6086129/80562509-40c08c00-89e8-11ea-970d-2bbd235d7b26.png)

**Comment by Bllacky** [comment]
Alright! Yes, I have exactly the same problem.

**Comment by damien-giry** [comment]
It seems that a "branch merge" delete a line in the file wwwroot/cgi-bin/plugins/geoip2_country.pm : 

![Snap1](https://user-images.githubusercontent.com/6086129/81141403-d28e4300-8f6c-11ea-87f1-15d0a84462f9.png)

**Comment by Bllacky** [comment]
I will try the above change as well and see if it works.

LE: I can confirm that the proposed fix at line 145 will fix the issue.

**Comment by vinixwu** [comment]
Thank you, @damien-giry, your solutioin works. :)

**Comment by kearva** [comment]
This was fixed by the merge in #178, so this issue can be closed.

**Comment by Bllacky** [comment]
Fixed as per merge.
