### ISSUE TITLE
I am looking for how to install on alpine linux with apache2

### ISSUE THREAD

**Issue by elico** [eldy/AWStats#182]
I installed alpine linux and ontop of it awstats.
I am a bit confused now since I am unable to make awstats work on it based on their tutorial:
https://wiki.alpinelinux.org/wiki/Awstats

Can anyone suggest on something?

Thanks,

**Comment by chuckhoupt** [comment]
That tutorial is over 7 years old so it is likely out of date. Also it uses the lighttpd web server rather then Apache. Since Alpine is commonly used for Docker images, you might look for AWStats Dockerfiles to use as a guide. For example:

https://github.com/pabra/docker_awstats

**Comment by elico** [comment]
@chuckhoupt Thanks.
