### ISSUE TITLE
SteamOS Debian distribution not detected

### ISSUE THREAD

**Issue by mdeguzis** [eldy/AWStats#19]
See:
https://sourceforge.net/p/awstats/feature-requests/887/

Please add SteamOS to the available detection list. I tried to add it in this post:
https://sourceforge.net/p/awstats/discussion/43428/thread/6871742e/?limit=25#882a

The unknown OS list is:

```
Unknown OS (useragent field)     
User agent (5)  Last visit
Debian_APT-HTTP/1.3_(1.0.10.2ubuntu1)   07 Jan 2016 - 05:37
Debian_APT-HTTP/1.3_(0.9.7.9)   07 Jan 2016 - 05:23
Debian_APT-HTTP/1.3_(1.0.9.8.1) 07 Jan 2016 - 05:22
Debian_APT-HTTP/1.3_(1.0.1ubuntu2)  06 Jan 2016 - 16:24
libwww-perl/6.08
```

You can view my stats page at:  
http://steamos-tools-stats.libregeek.org

Most of my traffic does\* come from APT, but there should be a way to detect SteamOS as an OS.

**Comment by eldy** [comment]
It seems nothing into the useragent string allows us to detect steam os.
The best we can do is report this as "debian". Done for next version
