### ISSUE TITLE
HowTo stop www.domain.com vs domain.com from being treated differently 

### ISSUE THREAD

**Issue by joshin42** [eldy/AWStats#231]
I have what I expect to be a really dumb question, but haven't found an answer in too-long of searching...

How can one redirect/rewrite www.domain.com/awstats as domain.com/awstats?

None of my normal Apache magic seems to work.

For AWStats, the domain(s) is(are) set up as the root - without the www.
but if one goes to www.domain.com, one gets 
'Error: Couldn't open config file "awstats.www.domain.com.conf" nor "awstats.conf".) '

Or how do I rewrite the request to point to awstats.domain.com.conf which exists

Sorry for the dumb question.

**Comment by visualperception** [comment]
You should be able to control what any connection to your websites show in a browser url.
i.e. domain.com or www.domain.com whichever you prefer. Can't remember exactly how to do it but it will be in your DNS management and the exact commands will be dependant on your specific dns host and its setup.
Hope this at least points you in the right direction.
Websites that are not your own will have to be done in awstats and I have no idea how that can be achieved.

**Comment by joshin42** [comment]
Thanks for the reply, but it wasn't sufficiently 'in-the-weeds' enough to be helpful. 

The problem seems to be how AWStats's Apache include file is set up. It uses alias and scriptalias, which creates havoc for using redirect in the Directory or Location. 

I may need to redo the include file from scratch using 'modern' Apache redirect/rewrite mechanisms. 
Will submit a pull request when I get around to putting a couple more hours into making a minor irritant go away. :)

**Comment by chuckhoupt** [comment]
From the error message, it sounds like one option would be to rename the config file to the default `awstats.conf`, but that may only be useful if only one site is hosted.

Another option is to explicitly give the name the config file. For example, the following:

    https://domain.com/awstats/awstats.pl?config=domain.com

That should use the config file `awstats.domain.com.conf`.

**Comment by chuckhoupt** [comment]
A follow-up. The default config name is derived from the CGI `SERVER_NAME` variable, which is set via Apache's [`ServerName`](https://httpd.apache.org/docs/2.4/mod/core.html#servername) directive. Here's the line where AWStats gets the default:

https://github.com/eldy/AWStats/blob/410c9a9dba5bbbfa9741b99aa82e319426aedffe/wwwroot/cgi-bin/awstats.pl#L17675

So for the default mechanism to work, the `ServerName` and config file name must match (i.e. either both with or without `www`).

**Comment by joshin42** [comment]
Got it, thanks all.

It's just a dumb annoyance that on their web sites, half my clients have the www and half don't, and explaining to the ones with www that they have to manually strip it for AWStats gets old.

That will work Chuck. I can manipulate the SERVER_NAME variable. Perfect, thanks!
