### ISSUE TITLE
Add geedo.com to bots

### ISSUE THREAD

**Issue by pappapo** [eldy/AWStats#248]
product-search-83-99-xxx-yy.geedo.com is registerad as a visitor but is clearly a bot so I kindly request it to be added to the robots file.

Thank you,
Per

**Comment by chuckhoupt** [comment]
Robots are generally blocked based on User-Agent string/header. What's this robot's User Agent?

**Comment by pappapo** [comment]
83.99.151.66 - - [16/Apr/2024:23:56:14 +0200] "GET /robots.txt HTTP/1.1" 301 242 "-" "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; GeedoProductSearch; +http://www.geedo.com/product-search.html) Chrome/79.0.3945.88 Safari/537.36"
