### ISSUE TITLE
Where to find raw logs with the plugin enabled?

### ISSUE THREAD

**Issue by dannybeckett** [eldy/AWStats#254]
With the `rawlog` plugin enabled, where should the option appear? I do not see it anywhere on the page and I don't see `raw` appear in the frame's source code.

I'm running AWStats 7.9 (build 20230108) on Plesk Obsidian 18.0.62 Update 1, Web Pro Edition

Thanks!

**Comment by chuckhoupt** [comment]
It should appear at the top of the stats frame. Here's an example:

<img width="951" alt="image" src="https://github.com/user-attachments/assets/c1e54034-42e7-4e44-bcc8-050a226cc863">

**Comment by dannybeckett** [comment]
> It should appear at the top of the stats frame. Here's an example:
> 
> <img alt="image" width="951" src="https://private-user-images.githubusercontent.com/1627217/350805516-c1e54034-42e7-4e44-bcc8-050a226cc863.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MDk0MTUsIm5iZiI6MTcyMTYwOTExNSwicGF0aCI6Ii8xNjI3MjE3LzM1MDgwNTUxNi1jMWU1NDAzNC00MmU3LTRlNDQtYmNjOC0wNTBhMjI2Y2M4NjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMDA0NTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWVhYWQ0OWVlOWNmMDY1M2MzMjIwODNlMjBmMDU1NGM1YjczZjdlZTUyMzliM2IzMGI3MzFlMWFmNjI2YmEyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WdgwW7No2Sd9Z1t2OA4j6ldh2coK_vBCk0eOPdJKN_g">

Thanks for the screenshot @chuckhoupt - maybe it’s a quirk of Plesk that the top bar doesn’t appear. I can see in the footer that the plugin is enabled. Perhaps it is due to the structure of the log files. No problem though.

Thanks for your help 🙂
