### ISSUE TITLE
Widen the widths of titles

### ISSUE THREAD

**Issue by dannybeckett** [eldy/AWStats#259]
In Advanced Web Statistics 7.9 (build 20230108), the width of titles such as "Summary" below are not wide enough:

![](https://private-user-images.githubusercontent.com/1627217/350805516-c1e54034-42e7-4e44-bcc8-050a226cc863.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NzI4MTEsIm5iZiI6MTcyMTY3MjUxMSwicGF0aCI6Ii8xNjI3MjE3LzM1MDgwNTUxNi1jMWU1NDAzNC00MmU3LTRlNDQtYmNjOC0wNTBhMjI2Y2M4NjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMTgyMTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjZjNWI1OWNlNzgzMTZjNjczMjk0ZDllZTlkNWI1NGFhNzY2YzQxMGVmNGJiMDEwNDNjNDRiM2ZhMjA1YTA1NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.o7ji4WnxaeUm_WCSU2EXNnEDWXNJGeeRYRFtv07NU1g)

A workaround is to use this option in your `.conf` file:

```
HTMLHeadSection="<style>    /* Widen section titles */ .aws_title { width: 100% !important; }    .aws_blank { display: none !important; }    </style>"
```

This fixes the width (ignore that mine is purple, that's a separate option):

![2024-07-22 19_24_08-AWStats for domain and 92 more pages - Personal - Microsoft​ Edge](https://github.com/user-attachments/assets/05e98063-36a4-4df2-94f0-cdaf1ca0719a)

**Comment by chuckhoupt** [comment]
Your first screenshot is missing, but I gather your concern is the 70% width on the `TD.aws_title` element? There is nothing to fix there -- the 70% width is a stylistic choice the author made for AWStats default "theme" (probably to make them look like tabs). Not an error to be corrected.

AWStats provides a variety of mechanisms to customize/theme its appearance:
- Simple logo/color customization of default theme using the `Logo` and `color_*` directives
- Advanced customization using the `StyleSheet` and `HTMLHeadSection` directives

Using the advanced mechanisms, we are all free to set the width we like. You like 100%, but I might prefer 50%. It's not "working around" a bug, it's supported advanced customization/theming.

Does this make sense? A good example of an advanced theme is: https://www.hackitu.de/awstats_theme/

**Comment by dannybeckett** [comment]
> Your first screenshot is missing, but I gather your concern is the 70% width on the `TD.aws_title` element? There is nothing to fix there -- the 70% width is a stylistic choice the author made for AWStats default "theme" (probably to make them look like tabs). Not an error to be corrected.
> 
> AWStats provides a variety of mechanisms to customize/theme its appearance:
> 
> * Simple logo/color customization of default theme using the `Logo` and `color_*` directives
> * Advanced customization using the `StyleSheet` and `HTMLHeadSection` directives
> 
> Using the advanced mechanisms, we are all free to set the width we like. You like 100%, but I might prefer 50%. It's not "working around" a bug, it's supported advanced customization/theming.
> 
> Does this make sense? A good example of an advanced theme is: https://www.hackitu.de/awstats_theme/

I have just updated the post, hopefully the first screenshot is showing now.

Yes that makes sense, thanks!
