### ISSUE TITLE
Alternative robots.pm search_engines.pm 

### ISSUE THREAD

**Issue by visualperception** [eldy/AWStats#37]
I have created alternative robots.pm and search_engines.pm.

These have been corrected and re-tested today ( I made mistakes in previous versions).

Where (and how) is the best  place to put them for anyone wanting to trial them? I'm not famliar with Github but have put files in fork visualperception/awstats for now if you want to try them out.
https://github.com/visualperception/awstats/tree/develop/wwwroot/cgi-bin/lib

The biggest change is that search_engines.pm now contains all google countries split by country code and normal or image searches.
Fact is that the vast majority of search engine visits come from google and having a split by country is useful.
I offer these files for possible inclusion into official release. Some people may find them useful.

I tested against a 1.4GB stats file (4 years logs from one site, just over 6 millions rows ) and compared timings with the standard search_engines.pm and robots.pm unedited from awstats 7.5. The times from the two runs were almost the same so the there is no performance penalty using these files. In fact the new files ran just a tad faster but bear in mind the new files are tuned to my site. Tune them to your own site and they should work just as well. i.e. put your sites most commonly used bots and engines at top of lists, especially google country code for your site.

**Comment by eldy** [comment]
PR was merged
