### ISSUE TITLE
country name not correct

### ISSUE THREAD

**Issue by sevdimali** [eldy/AWStats#76]
Hi, for country name Azerbaijan. in Awstat it is **Azerbaidjan**
but it has to be change to
**Azerbaijan**.

**Comment by AnthonyBe** [comment]
As a temporary fix, you can manually edit the \cgi-bin\lib\domains.pm file with a text editor and change line 30 from

`'az','Azerbaidjan','ba','Bosnia-Herzegovina','bb','Barbados',`

to 

`'az','Azerbaijan','ba','Bosnia-Herzegovina','bb','Barbados',`

**Comment by sevdimali** [comment]
Hi, thanks for commit. issue solved.
