### ISSUE TITLE
Add support for Microsoft Edge

### ISSUE THREAD

**Issue by csware** [eldy/AWStats#8]
https://msdn.microsoft.com/library/Hh869301(v=VS.85).aspx explains the UserAgent string.

**Comment by ursNiemi** [comment]
Edge browser, for some reason, has `Chrome/xxx.yyy.zz Safari/xxx.yyy` in the UserAgent field, which hits the hard-coded regexp in awstats.pl. So it's not possible to work around by editing browsers.pm. (Same with latest mobile IE 11, it seems.)

**Comment by dcaillibaud** [comment]
But they signed also with Edge (https://msdn.microsoft.com/en-us/library/hh869301%28v=vs.85%29.aspx), it shoud be possible to add an $regveredge in awstats.pl and check it before Chrome and Safari

**Comment by avian2** [comment]
I made a pull request that fixes this: https://github.com/eldy/awstats/pull/22

**Comment by eldy** [comment]
Will be available with 7.5
