### ISSUE TITLE
.txt files are listed as "download"

### ISSUE THREAD

**Issue by csware** [eldy/AWStats#9]
Text files (.txt) are listed as download. Is there a reason for that?

Normally .txt fiels are served by the browser as any other page and displayed w/o the need for downloading.

**Comment by eldy** [comment]
Web sites build with .txt page are very rare.
In most cases, when a link point to a .txt file, goal is to allow user to get/download the .txt and not to provide an www experience, that's why .txt ae counted as download on purpose.
